config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  get 'about' => 'static_pages#about', as: :about
  get 'contact' => 'static_pages#contact', as: :contact

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'blog_posts#index'

  '''
  GET    /blog_posts          blog_posts#index
  POST   /blog_posts          blog_posts#create
  GET    /blog_posts/new      blog_posts#new
  GET    /blog_posts/:id/edit blog_posts#edit
  GET    /blog_posts/:id      blog_posts#show
  PATCH  /blog_posts/:id      blog_posts#update
  PUT    /blog_posts/:id      blog_posts#update
  DELETE /blog_posts/:id      blog_posts#destroy
  '''
  resources :blog_posts, :except => [:about, :contact, :browse]
  get 'browse' => 'blog_posts#browse', as: :browse

  devise_for :users
  resources :users, :except => [:create, :new]

  post 'create_user' => 'users#create', as: :create_user
  get 'new_user' => 'users#new', as: :new_user

  resources :tags

  resources :authors

  resources :static_pages

  resources :subscribers, :except => [:new, :show, :edit, :index, :update, :destroy]

  get 'unsubscribe/:token' => 'subscribers#destroy', as: :unsubscribe

  # via all means any type of request(get, post, etc.)
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/blog_post.rb
# require 'uri'

class BlogPost < ApplicationRecord
  attr_accessor :image_url
  attr_accessor :author_name

  before_create :book_cover_from_url
  before_create :author_from_author_name

  before_update :book_cover_from_url
  before_update :author_from_author_name

  has_attached_file :book_cover, styles: {
    index: '200x300>',
    full: '314x475>'
  }

  def book_cover_from_url
    if image_url != ""
      self.book_cover = URI.parse(image_url)
    end
  end

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :book_cover, :content_type => /\Aimage\/.*\Z/

  self.per_page = 6

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id? #will change the slug if the name changed
    slug.blank? || title_changed?
  end

  validates :title, presence: true
  validates :body, presence: true # , length: { maximum: 40000 }
  # REMEMBER TO UPDATE CONTROLLER TO ALLOW NEW FIELDS
  # validates :rating, numericality: { only_decimal: true }

  # enables us to access all tags for a blog post through blog_post.tags
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_list
    self.tags.collect do |tag|
      # otherwise returns an array of tag objects, not tag names
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  belongs_to :author
  
  def author_from_author_name
    if author_name != ""
      self.author_id = Author.find_or_create_by(name: author_name).id
      # self.author_name = Author.find(self.author_id).name
    end
  end
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show, :browse]

  def index
    # From most recent to least
    # @blog_posts = BlogPost.order("created_at ASC").all

    # per_page is defined in blog post model
    @blog_posts = BlogPost.order('created_at DESC').page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @subscriber = Subscriber.new

    # Note the friendly! It's necessary for use with friendly_id
    @blog_post = BlogPost.friendly.find(params[:id])

    @posted = "Posted: " + @blog_post.created_at.strftime("%B %d, %Y")
    @updated = ""
    if @blog_post.created_at.strftime("%B %d %Y") != @blog_post.updated_at.strftime("%B %d %Y")
      @updated = "Last updated: " + @blog_post.updated_at.strftime("%B %d, %Y")
    end
    # if user requests old url for post, redirect them to the new url
    if request.path != blog_post_path(@blog_post)
      redirect_to @blog_post, status: :moved_permanently
    end
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.friendly.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post
    else
      render 'new'
    end
  end

  def update
    @blog_post = BlogPost.friendly.find(params[:id])
    '''
    unless params[:blog_post][:image_url] == ""
      @blog_post.book_cover_from_url(params[:blog_post][:image_url])
    end
    '''

    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render 'edit'
    end
  end

  def destroy
    @blog_post = BlogPost.friendly.find(params[:id])
    @blog_post.destroy
 
    redirect_to blog_posts_path
  end

  def browse
  end

  private
    def blog_post_params
      params.require(:blog_post).permit(:title, :book_cover, :image_url, :body, :rating, :tag_list, :author_name) # , :author
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_blog_post_author.html.erb
<div class="post-meta">
  <p>
  <%= @posted %>
  <% if @updated != "" %>
    <span> | </span>
    <%= @updated %>
  <% end %>
  </p>
</div>

<% if @blog_post.rating %>
  <div id="rating">
    <div id="rating-label">Rating: </div>
    <%= content_tag :div, "", id: "rateYo", data: { rating: @blog_post.rating } %>
  </div>
<% end %>

<!--
<div id="author-info">
  <%= link_to 'Blog Author Name', about_path %>
  <%= link_to 'Contact', contact_path %>
</div>
-->

app/views/blog_posts/_blog_post_links.html.erb
<div class="blog-post-links">
  <%= link_to 'Read More', blog_post_path(blog_post) %>
  <% if user_signed_in? %>
    <%= " | " %>
    <%= link_to 'Edit', edit_blog_post_path(blog_post) %>
    <%= " | " %>
    <%= link_to 'Delete', blog_post_path(blog_post),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/blog_posts/_blog_post_tags.html.erb
<!-- <div id="tag-heading">Tags:</div> -->
<div class="tag-container">
  <% blog_post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: 'tag-link' %>
  <% end %>
</div>

app/views/blog_posts/_form.html.erb
<%= simple_form_for @blog_post do |f| %>

  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog_post.errors.count, "error") %> prohibited
        this blog_post from being saved:
      </h2>
      <ul>
        <% @blog_post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :author_name %>
  <!-- <%= f.input :book_cover %> -->
  <%= f.input :image_url, as: :url %>
  <%= f.input :body, as: :summernote %>
  <%= f.input :rating, collection: [1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0] %>
  <%= f.input :tag_list %>
  <%= f.button :submit, class: 'btn btn-primary' %>
 
<% end %>

app/views/blog_posts/_post_date.html.erb
<!-- requires vairables created_at and updated_at -->
<p class="post-meta">
  <%= "Posted: " %> 
  <%= local_date(created_at, "%B %d, %Y") %>
  <% if local_date(created_at, "%B %d, %Y") != local_date(updated_at, "%B %d, %Y") %>
    <%= " | Last updated: " %>
    <%= local_date(updated_at, "%B %d, %Y") %>
  <% end %>
</p>

app/views/blog_posts/_post_preview.html.erb
<div class="post-preview">
  <!-- Look into cleaning this up -->
  <%= link_to blog_post_path(blog_post) do %>
    <h2 class="post-preview-title">
      <%= blog_post.title %>
      <% if blog_post.author_id %>
        <%= " by " %>
        <% author = Author.find(blog_post.author_id) %>
        <%= link_to author.name, author_path(author), class: "author-link" %>
      <% end %>
    </h2>
  <% end %>

  <div class="row">
    <div class="col-md-3 hidden-sm-down post-preview-left">
      <%= image_tag(blog_post.book_cover.url(:index), alt: "Book Cover", class: "img-responsive") %>
      <br>
      <!--
      <div class="col-lg-6">
        <%= image_tag("http://d.gr-assets.com/misc/1454549143-1454549143_goodreads_misc.png",
          alt: "Goodreads logo", class: "img-responsive external-link") %>

        <%= image_tag("http://vignette3.wikia.nocookie.net/logopedia/images/e/ee/Google_Play_logo.png/revision/latest?cb=20150902024443",
          alt: "Goodreads logo", class: "img-responsive external-link") %>
      </div>

      <div class="col-lg-6">
        <%= image_tag("https://s3.amazonaws.com/BURC_Pages/downloads/a-smile_color_btn.png",
          alt: "Goodreads logo", class: "img-responsive external-link") %>

        <%= image_tag("https://cdn3.iconfinder.com/data/icons/social-icons-5/607/Twitterbird.png",
          alt: "Goodreads logo", class: "img-responsive external-link") %>
      </div>
      -->
    </div>
    <div class="col-md-9 post-preview-right">
      <!-- truncates posts to 500 char or less
        separator: ' ' means it will not stop in the middle of a word 
        escape: false basically means html will get displayed properly, 
        instead of being escaped into <p><ul>, etc. tags -->
      <%= truncate_html(blog_post.body.html_safe, length: 400, separator: ' ', escape: false) %>
      <%= render 'blog_posts/blog_post_links', blog_post: blog_post %>
    </div>
  </div>
  <%= render 'blog_posts/blog_post_tags', blog_post: blog_post %>
</div>

<hr>

app/views/blog_posts/browse.html.erb
<header class="intro-header">
  <div class="site-heading">
    <h1>
      <%= "Browse by " %>
    </h1>

    <h1>
      <%= link_to "tags", tags_path, class: 'tag-link' %>
      <%= link_to "authors", authors_path, class: 'author-link'%>    
    </h1>
  </div>
</header>

app/views/blog_posts/edit.html.erb
<h1>Edit Post</h1>

<article>
  <%= render 'form' %>
</article>

app/views/blog_posts/index.html.erb
<%= render 'layouts/header' %>

<% @blog_posts.each do |blog_post| %>
  <%= render 'post_preview', blog_post: blog_post %>
<% end %>

<%= will_paginate @blog_posts, class: 'text-center' %>

app/views/blog_posts/index.js.erb
/*
$('#my-posts').append('<%= j render @blog_posts %>');
<% if @blog_posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @blog_posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>
*/

app/views/blog_posts/new.html.erb
<h1>New Post</h1>

<article>
  <%= render 'form' %>

  <div class="container blog-post-links">
    <div class="row">
      <%= link_to 'Back', blog_posts_path %>
    </div>
  </div>
</article>

app/views/blog_posts/show.html.erb
<article>
  <h2 class="blog-post-title">
    <%= @blog_post.title %>
    <% if @blog_post.author_id %>
      <%= " by " %>
      <% author = Author.find(@blog_post.author_id) %>
      <%= link_to author.name, author_path(author), class: "author-link" %>
    <% end %>
  </h2>

  <div class="col-lg-4 col-md-4 post-preview-left">
    <%= image_tag(@blog_post.book_cover.url(:full), alt: "Book Cover", class: "img-responsive") %>
  </div>

  <%= @blog_post.body.html_safe %>

  <%= render 'blog_posts/blog_post_author' %>

  <div class="tag-container">
  <% @blog_post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: 'tag-link' %>
  <% end %>
  </div>

  <div id="author-info"></div>

  <% if user_signed_in? %>
    <div class="blog-post-links">
      <!-- <%= link_to 'Back', root_path %>
      <%= " | " %>  -->
      <%= link_to 'Edit', edit_blog_post_path(@blog_post) %>
      <%= " | " %>
      <%= link_to 'Delete', blog_post_path(@blog_post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

  <div id="subscriber_email">
    <%= render 'subscribers/form' %>
  </div>
  
  <!--
  <% #Inefficient %>
  <% if @blog_post.author_id and Author.find(@blog_post.author_id).info %>
    <h4>
      <%= "About " %>
      <%= link_to author.name, author_path(author), class: "author-link" %>
    </h4>
    <%= Author.find(@blog_post.author_id).info.html_safe %>
  <% end %>
  -->
</article>