config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  get 'about' => 'static_pages#about', as: :about
  get 'contact' => 'static_pages#contact', as: :contact

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'blog_posts#index'

  '''
  GET    /blog_posts          blog_posts#index
  POST   /blog_posts          blog_posts#create
  GET    /blog_posts/new      blog_posts#new
  GET    /blog_posts/:id/edit blog_posts#edit
  GET    /blog_posts/:id      blog_posts#show
  PATCH  /blog_posts/:id      blog_posts#update
  PUT    /blog_posts/:id      blog_posts#update
  DELETE /blog_posts/:id      blog_posts#destroy
  '''
  resources :blog_posts, :except => [:about, :contact, :browse]
  get 'browse' => 'blog_posts#browse', as: :browse

  devise_for :users
  resources :users, :except => [:create, :new]

  post 'create_user' => 'users#create', as: :create_user
  get 'new_user' => 'users#new', as: :new_user

  resources :tags

  resources :authors

  resources :static_pages

  resources :subscribers, :except => [:new, :show, :edit, :index, :update, :destroy]

  get 'unsubscribe/:token' => 'subscribers#destroy', as: :unsubscribe

  # via all means any type of request(get, post, etc.)
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/author.rb
class Author < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id? #will change the slug if the name changed
    slug.blank? || name_changed?
  end

  has_many :blog_posts
  has_many :author_links

  def to_s
    @name
  end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @authors = Author.joins(:blog_posts).group("authors.id").order("count(blog_posts.id) DESC") # left_outer_joins to include authors with 0 posts
  end

  def show
    @author = Author.friendly.find(params[:id])
    @author_blog_posts = Author.friendly.find(params[:id]).blog_posts.paginate(page: params[:page], per_page: 10)
    @authors = Author.joins(:blog_posts).group("authors.id").order("count(blog_posts.id) DESC")
    
    '''
    respond_to do |format|
      format.html
      format.js
    end
    '''
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.friendly.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def update
    @author = Author.friendly.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.friendly.find(params[:id])
    if @author.blog_posts.count == 0
      @author.destroy
      redirect_to authors_path
    else
      flash.alert = "Error: cannot delete author that is connected to any blog posts"
      redirect_to @author
    end
  end

  private
    def author_params
      params.require(:author).permit(:name, :info)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:
      </h2>
      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :info, as: :summernote %>

  <%= f.button :submit, class: 'btn btn-primary' %>
 
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<article>
  <%= render 'form' %>
</article>

app/views/authors/index.html.erb
<header class="intro-header">
  <div class="site-heading">
    <h1>Browse by author</h1>
  </div>
</header>

<% @authors.each do |author| %>
  <%= link_to "#{author.name} #{author.blog_posts.count}", author_path(author), class: 'author-link' %>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<article>
  <%= render 'form' %>
</article>

app/views/authors/show.html.erb
<header class="intro-header">
  <div class="site-heading">
    <h1><%= link_to @author.name, author_path(@author.name), class: 'author-link' %></h1>
  </div>
</header>

<% if @author.info %>
  <div id="author-info"><%= @author.info.html_safe %></div>
<% end %>

<% if user_signed_in? %>
  <div class="blog-post-links">
    <%= link_to 'Edit', edit_author_path(@author) %>
    <%= " | " %>
    <%= link_to 'Delete', author_path(@author),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

<hr>

<!-- <header class="intro-header">
  <h2>Posts about <%= link_to @author.name, author_path(@author), class: "author-link" %></h2>
</header> -->

<!-- <div class="author-container">
<% @authors.each do |a| %>
  <% unless a.blog_posts.count == 0 %>
    <%= link_to "#{a.name} #{a.blog_posts.count}", author_path(a), class: 'author-link' %>
  <% end %>
<% end %>
</div> -->

<% @author_blog_posts.each do |blog_post| %>
  <%= render 'blog_posts/post_preview', blog_post: blog_post %>
<% end %>

<%= will_paginate @author_blog_posts %>