config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  get 'about' => 'static_pages#about', as: :about
  get 'contact' => 'static_pages#contact', as: :contact

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'blog_posts#index'

  '''
  GET    /blog_posts          blog_posts#index
  POST   /blog_posts          blog_posts#create
  GET    /blog_posts/new      blog_posts#new
  GET    /blog_posts/:id/edit blog_posts#edit
  GET    /blog_posts/:id      blog_posts#show
  PATCH  /blog_posts/:id      blog_posts#update
  PUT    /blog_posts/:id      blog_posts#update
  DELETE /blog_posts/:id      blog_posts#destroy
  '''
  resources :blog_posts, :except => [:about, :contact, :browse]
  get 'browse' => 'blog_posts#browse', as: :browse

  devise_for :users
  resources :users, :except => [:create, :new]

  post 'create_user' => 'users#create', as: :create_user
  get 'new_user' => 'users#new', as: :new_user

  resources :tags

  resources :authors

  resources :static_pages

  resources :subscribers, :except => [:new, :show, :edit, :index, :update, :destroy]

  get 'unsubscribe/:token' => 'subscribers#destroy', as: :unsubscribe

  # via all means any type of request(get, post, etc.)
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, uniqueness: true
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create
    @subscriber = Subscriber.new(subscriber_params)
    @subscriber.save
  end

  def destroy
    email = Rails.application.message_verifier(:token).verify(params[:token])
    @subscriber = Subscriber.find_by(email: email)
    @subscriber.destroy

    flash[:notice] = "Successfully unsubscribed"
    redirect_to root_path
  end

  private
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
  def send_all_emails
    subscribers = Subscriber.all
    # recent_posts = BlogPost.where("created_at >= ?", 1.week.ago.utc).order("created_at DESC")

    subscribers.each do |s|
      SubscriptionMailer.send_email(s).deliver_later
    end
  end
end

app/views/subscribers/_form.html.erb
<div id="email_form_contents">
<h4>Want to get weekly updates on what Hope's been reading? Subscribe here!</h4>

<%= form_for @subscriber, html: { autocomplete: 'off' } do |f| %>
  <%= f.text_field :email %>
  <%= f.submit 'Subscribe', class: 'btn btn-primary', id: 'email_subscribe_button', :"data-no-turbolink" => true %>
<% end %>
</div>

<p id="email_form_success">Thanks!</p>

app/views/subscribers/show.html.erb
<p><%= @subscriber.email %></p>
<%= link_to 'Delete', subscriber_path(@subscriber),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>