config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  get 'about' => 'static_pages#about', as: :about
  get 'contact' => 'static_pages#contact', as: :contact

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'blog_posts#index'

  '''
  GET    /blog_posts          blog_posts#index
  POST   /blog_posts          blog_posts#create
  GET    /blog_posts/new      blog_posts#new
  GET    /blog_posts/:id/edit blog_posts#edit
  GET    /blog_posts/:id      blog_posts#show
  PATCH  /blog_posts/:id      blog_posts#update
  PUT    /blog_posts/:id      blog_posts#update
  DELETE /blog_posts/:id      blog_posts#destroy
  '''
  resources :blog_posts, :except => [:about, :contact, :browse]
  get 'browse' => 'blog_posts#browse', as: :browse

  devise_for :users
  resources :users, :except => [:create, :new]

  post 'create_user' => 'users#create', as: :create_user
  get 'new_user' => 'users#new', as: :new_user

  resources :tags

  resources :authors

  resources :static_pages

  resources :subscribers, :except => [:new, :show, :edit, :index, :update, :destroy]

  get 'unsubscribe/:token' => 'subscribers#destroy', as: :unsubscribe

  # via all means any type of request(get, post, etc.)
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id? #will change the slug if the name changed
    slug.blank? || name_changed?
  end

  has_many :blog_posts
  has_many :author_links

  def to_s
    @name
  end
  
end

app/models/author_link.rb
class AuthorLink < ApplicationRecord
end

app/models/blog_post.rb
# require 'uri'

class BlogPost < ApplicationRecord
  attr_accessor :image_url
  attr_accessor :author_name

  before_create :book_cover_from_url
  before_create :author_from_author_name

  before_update :book_cover_from_url
  before_update :author_from_author_name

  has_attached_file :book_cover, styles: {
    index: '200x300>',
    full: '314x475>'
  }

  def book_cover_from_url
    if image_url != ""
      self.book_cover = URI.parse(image_url)
    end
  end

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :book_cover, :content_type => /\Aimage\/.*\Z/

  self.per_page = 6

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id? #will change the slug if the name changed
    slug.blank? || title_changed?
  end

  validates :title, presence: true
  validates :body, presence: true # , length: { maximum: 40000 }
  # REMEMBER TO UPDATE CONTROLLER TO ALLOW NEW FIELDS
  # validates :rating, numericality: { only_decimal: true }

  # enables us to access all tags for a blog post through blog_post.tags
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_list
    self.tags.collect do |tag|
      # otherwise returns an array of tag objects, not tag names
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  belongs_to :author
  
  def author_from_author_name
    if author_name != ""
      self.author_id = Author.find_or_create_by(name: author_name).id
      # self.author_name = Author.find(self.author_id).name
    end
  end
  
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, uniqueness: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id? #will change the slug if the name changed
    slug.blank? || name_changed?
  end

  has_many :taggings
  has_many :blog_posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :blog_post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @authors = Author.joins(:blog_posts).group("authors.id").order("count(blog_posts.id) DESC") # left_outer_joins to include authors with 0 posts
  end

  def show
    @author = Author.friendly.find(params[:id])
    @author_blog_posts = Author.friendly.find(params[:id]).blog_posts.paginate(page: params[:page], per_page: 10)
    @authors = Author.joins(:blog_posts).group("authors.id").order("count(blog_posts.id) DESC")
    
    '''
    respond_to do |format|
      format.html
      format.js
    end
    '''
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.friendly.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def update
    @author = Author.friendly.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.friendly.find(params[:id])
    if @author.blog_posts.count == 0
      @author.destroy
      redirect_to authors_path
    else
      flash.alert = "Error: cannot delete author that is connected to any blog posts"
      redirect_to @author
    end
  end

  private
    def author_params
      params.require(:author).permit(:name, :info)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.friendly.find(params[:id])
    @tag_blog_posts = Tag.friendly.find(params[:id]).blog_posts.paginate(page: params[:page], per_page: 10)
    @tags = Tag.joins(:blog_posts).group("tags.id").order("count(blog_posts.id) DESC")
    
    respond_to do |format|
      format.html
      format.js
    end

    # if user requests old url for post, redirect them to the new url
    if request.path != tag_path(@tag)
      redirect_to @tag, status: :moved_permanently
    end
  end
  
  def index
    # Gets all tags and orders them from most blog posts to least
    @tags = Tag.joins(:blog_posts).group("tags.id").order("count(blog_posts.id) DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_admin, :only => [:create, :new]

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Hope Speaks Volumes"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end 
  end

  '''
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
  '''
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
  def send_all_emails
    subscribers = Subscriber.all
    # recent_posts = BlogPost.where("created_at >= ?", 1.week.ago.utc).order("created_at DESC")

    subscribers.each do |s|
      SubscriptionMailer.send_email(s).deliver_later
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p class="copyright text-muted">&copy; Hope Speaks Volumes 2016</p>
</footer>

app/views/layouts/_header.html.erb
<header class="intro-header">
  <div class="site-heading">
    <h1>Hope Speaks Volumes</h1>
    <hr class="small">
    <span class="subheading">A Book Review Blog</span>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<!-- Re-examine this later -->
<nav class="navbar navbar-fixed-top navbar-default">
  <!-- Might be better to go with just container, come back to this -->
  <div class="container-fluid">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        Menu <i class="fa fa-bars"></i>
      </button>
      <%= link_to "Hope Speaks Volumes", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_blog_post_path %></li>
          <li role="separator" class="divider"></li>
        <% end %>
        <li><%= link_to "Browse", browse_path %></li>
        <!-- <li><%= link_to "Search", '#' %></li> -->
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if user_signed_in? %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- Look up what this means -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Look up what this means -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <title><%= full_title(yield(:title)) %></title>

    <!-- RateYo Plugin for 5 Star Rating -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.1.1/jquery.rateyo.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.1.1/jquery.rateyo.min.js"></script>

    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

    <!-- Font - Raleway -->
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <!-- navbar-inverse makes the navbar dark instead of light -->
    <%= render 'layouts/navbar' %>
    <div class="container col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="buffer-container col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="body-container">
          <!-- Code to display flash messages -->
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
          <!-- Show debug info if in the development environment (not in production) -->
          <!-- <%= debug(params) if Rails.env.development? %> -->

        </div>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>